### ISSUE TITLE
Again lexical error

### ISSUE THREAD

**Issue by AlexQnx** [christophergandrud/imfr#10]
Probably I'm doing something wrong, but I started to get the same error discussed in the previous issue: 
 Error: lexical error: invalid char in json text.
                                       <html><head><title>Request Reje
                     (right here) ------^
I have updated to the latest package from github (devtools::install_github('christophergandrud/imfr')) but the error is still there. 
Moreover I tried to download data directly from IMF using generated url:
http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/IFS/.AD+AE+AF+DD+DE.PCPI_IX?startPeriod=2010&endPeriod=2017
and received the following error:  

The requested URL was rejected. Please consult with your administrator.
Your support ID is: 384838716675644175

I tried different browsers (IE, Chrome) but had the same result, maybe there are some issues with internet settings, as I'm behind the proxy.

**Comment by christophergandrud** [comment]
Could you send a reproducible example? That would help a lot.

**Comment by AlexQnx** [comment]
This is actually standard request:
library(imfr)
packageVersion("imfr")
[1] ‘0.1.4’

rates <- imf_data(database_id = 'IFS', indicator = c('PCPI_IX', 'FPOLM_PA','LUR_PT'), freq = 'M', start = 2010,  print_url=TRUE)

Attempting to download from: http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/IFS/.AD+AE+AF+AG+AI+AL+AM+AN+AO+AQ+AR+AS+AT+AU+AW+AX+AZ+BA+BB+BD+BE+BF+BG+BH+BI+BJ+BL+BM+BN+BO+BQ+BR+BS+BT+BV+BW+BY+BZ+CA+CC+CD+CF+CG+CH+CI+CK+CL+CM+CN+CO+CR+CS+CU+CV+CW+CX+CY+CZ+DD+DE.PCPI_IX?startPeriod=2010&endPeriod=2017

Downloading: 190 B     
 Show Traceback
Error: lexical error: invalid char in json text.
                                       <html><head><title>Request Reje
                     (right here) ------^

**Comment by arthurwelle** [comment]
Hi there, same problem here!

Loading required package: imfr
> packageVersion("imfr")
[1] ‘0.1.4’

> real_ex <- imf_data(database_id = 'IFS', indicator = 'EREER_IX',
+                     country = c('CN', 'GB'), freq = 'A')
Downloading: 170 B     
Error: lexical error: invalid char in json text.
                                       <html><head><title>Request Reje
                     (right here) ------^

**Comment by christophergandrud** [comment]
Is it still a problem?

Sometimes the IMF end goes down, but I am now able to successfully complete these requests.

**Comment by christophergandrud** [comment]
I'll close this issue, but feel free to reopen if still a problem.
