### ISSUE TITLE
Code that worked last week spits out error

### ISSUE THREAD

**Issue by zenteknet** [christophergandrud/imfr#13]
Hi. This code:

df3 = imf_data(database_id = 'IFS', indicator = 'FM0_XDC',
                    country = c("W0","US", 'U2', "CN", "JP", "GB" ), freq = 'M',
                    start = 1999, end = current_year(), print_url = FALSE)

which worked last week now returns:
Downloading: 170 B     Error: lexical error: invalid char in json text.
                                       <html><head><title>Request Reje
                     (right here) ------^

They must have changed something which is a bummer. Thanks Bruce

Sorry, apparently the IMF was blocking my Private Internet Access VPN, which caused the problem. Thanks

**Comment by cjyetman** [comment]
It works for me. What version of `imfr` are you using?

Trying setting `print_url = TRUE`, then copy-paste the URL it prints into a browser. Maybe you're IP is being blocked?

**Comment by christophergandrud** [comment]
I was unable to reproduce this issue with version 0.1.6.
