### ISSUE TITLE
Euro Area country code

### ISSUE THREAD

**Issue by gamrot** [christophergandrud/imfr#15]
I was trying to find a iso2c country code for Euro Area --- it seems that it's not there.

I've tried this code (trying to look for `Domestic Currency per U.S. Dollar, Period Average` --- which is reported as one of the Exchange rates indicators):

`
imf_df <- imf_data(database_id = 'IFS',
                   indicator = 'ENDA_XDC_USD_RATE',
                   country = 'all', freq = 'A',
                   start = 2010, end = current_year())`

I've tried to use EU, but this also does not work. There is also nothing remotely related to Euro Zone in the file related to `country = 'all'` that can be found here: https://github.com/christophergandrud/imfr/blob/master/data/all_iso2c.csv

**Comment by gamrot** [comment]
I think I've found the answer on my own using IMFData Package. Turns out there are many special country codes hidden in the API. You can find them all (for `IFS` database) by:

`
install.packages('IMFData')

library(IMFData)

IFS.available.codes <- DataStructureMethod('IFS')

names(IFS.available.codes)

IFS.available.codes[[2]] %>% View
`

**Comment by gamrot** [comment]
I think I've found the answer on my own using IMFData Package. Turns out there are many special country codes hidden in the API. You can find them all (for `IFS` database) by:

```
install.packages('IMFData')
library(IMFData)

IFS.available.codes <- DataStructureMethod('IFS') 
names(IFS.available.codes)  
IFS.available.codes[[2]] %>% View
```

**Comment by cjyetman** [comment]
Yes, Euro Area does not have an iso2c code, so IMF uses a special code.

```r
library(imfr)

imf_codelist("IFS")
# Downloading: 40 kB               codelist        description
# 1     CL_UNIT_MULT              Scale
# 2          CL_FREQ          Frequency
# 3      CL_AREA_IFS Geographical Areas
# 4 CL_INDICATOR_IFS          Indicator
# 5   CL_TIME_FORMAT        Time format

codes <- imf_codes("CL_AREA_IFS")
codes[grepl("Euro", codes$description), ]
# codes
# 74      U2
# 75      4F
# 247 1C_904
# 254 1C_903
# 257     E1
# description
# 74  Euro area (Member States and Institutions of the Euro Area) changing composition
# 75                                                       ECB (European Central Bank)
# 247                                                       Central and eastern Europe
# 254                                                   Emerging and Developing Europe
# 257                                                                           Europe


imf_data(database_id = 'IFS', indicator = 'ENDA_XDC_USD_RATE', 
         country = 'U2', freq = 'A', start = 2010, end = current_year())
# |============================| 100%
# iso2c year ENDA_XDC_USD_RATE
# 1    U2 2010         0.7543090
# 2    U2 2011         0.7184139
# 3    U2 2012         0.7783381
# 4    U2 2013         0.7529451
# 5    U2 2014         0.7527282
# 6    U2 2015         0.9012964
# 7    U2 2016         0.9034214
# 8    U2 2017         0.8852055
# 9    U2 2018         0.8467727
```
