### ISSUE TITLE
Error returned by imf_data under return_raw=T

### ISSUE THREAD

**Issue by giannilmbd** [christophergandrud/imfr#16]
Hi,
Running this commands

```r
database_id="IFS"
t1<-imf_codelist(database_id, return_raw = FALSE, times = 3)
test = imf_codes(codelist = t1$codelist[4])
t2<-grep(x=test$description,pattern = "[Ee]xchange Rates")
destc<-test$description[t2]
codes<-test$codes[8]
gg<-imf_data(database_id, codes, country = "all", start = 2000,
         end = current_year(), freq = "Q", return_raw = F,
         print_url = T, times = 3)
```

I get the following error

> Error in `[.data.frame`(sub_data, , indicator) : 
  undefined columns selected

Is this a known problem? Any suggestion?
Thanks 
Gianni

**Comment by christophergandrud** [comment]
The `codes` object you created is a factor, not the required `character` class. 

I've updated the function so that they error message is more informative: 41aeab8d70941aa62f76d23e95ae18f24211086f

In your case, just use:

```R
gg<-imf_data(database_id, as.character(codes), country = "all", start = 2000,
             end = current_year(), freq = "Q", return_raw = F,
             print_url = T, times = 3)
```

to convert `codes` to a character.

**Comment by giannilmbd** [comment]
Thanks!
Gianni
