### ISSUE TITLE
Database ids

### ISSUE THREAD

**Issue by jciconsult** [christophergandrud/imfr#17]
In your examples,  you use a database of BOP.
When I retrieve the database ids,  I do not see that in the table.  What am I missing?

**Comment by christophergandrud** [comment]
Thanks for highlighting. There appears to be some change to the IMF schema for their database IDs. 

Balance of Payments (`BOP`) should still work for `imf_data`. 

Still need to figure out what they changed in the schema.

**Comment by christophergandrud** [comment]
Solved in ae1c2dd49c021eaa48871f6fd2df0376a3e4b886
