### ISSUE TITLE
Missing Counterpart DOT

### ISSUE THREAD

**Issue by msgoussi** [christophergandrud/imfr#21]
DOT database has counterpart country, ie Country/area is trading with other country/area.
imf_codes(codelist = 'CL_INDICATOR_DOT')

when I run the following code, i can not find the counterpart area column

imf_data("DOT", indicator = "TXG_FOB_USD", country = "US",
         start = 2018, end = current_year(), 
         freq = "A")

can we use ios3 instead of iso2, the reason behind is Nambia iso2 is NA, so when you save the dataframe, NA becomes a Missing value. 
Thanks

**Comment by cjyetman** [comment]
related to #22
