### ISSUE TITLE
One of country is not there

### ISSUE THREAD

**Issue by msgoussi** [christophergandrud/imfr#23]
c("FCAA_NUM", "FCAC_NUM", "FCBODCA_NUM") %>% 
    imfr::imf_data('FAS', indicator = ., freq = 'A', return_raw = FALSE)
Nambia (iso2 : NA) is not there.

**Comment by christophergandrud** [comment]
Hi @msgoussi could you provide some more details about this issue. Is it that Namibia is missing? 

Note Namibia's ISO2C code is "NA". This is confusing in R, but not really an issue I can "fix" in the package.

**Comment by msgoussi** [comment]
Yes, Namibia is missing since its iso2 is NA

**Comment by christophergandrud** [comment]
Dug into it more. The problem is that "NA" was not in the list of ISO2C codes the package uses internally to cleanup the downloaded data. Fix https://github.com/christophergandrud/imfr/commit/520c6c2de3280f6b90fbc667bca50046c0f21932#diff-81aad01df2cc85eeb91cdc0a302b059d Should be on CRAN soon.
