### ISSUE TITLE
Resolving host name

### ISSUE THREAD

**Issue by sedes08** [christophergandrud/imfr#3]
Hello, 

while testing some of the examples I got the following error:
real_ex <- imf_data(database_id = 'IFS', indicator = 'EREER_IX', country = c('CN', 'GB'), freq = 'A')

Error in curl::curl_fetch_memory(url, handle = handle) : 
Couldn't resolve host name

**Comment by christophergandrud** [comment]
Thanks for the note. I wasn't able to reproduce the problem could you provide more information about what version you are using and your system?
