### ISSUE TITLE
imf_data no country filter possible

### ISSUE THREAD

**Issue by datapumpernickel** [christophergandrud/imfr#31]
Hi,

this is a great package and has already saved me tons of work - so thank you! 
I am currently running into an issue, where I am not sure, whether this is related to your package or the IMF-API. 
That is why I posted it on stackoverflow, but cross-posting here, hoping someone might know how to help with this. 
https://stackoverflow.com/questions/66866550/querying-imf-api-with-imfr-error-no-result-does-not-accept-filter 

Thanks!

**Comment by cjyetman** [comment]
You can use the `print_url = TRUE` argument to see the actual API call.

With...
``` r
imf_data(database_id = "DOT", indicator = c("TMG_FOB_USD"), 
         country = c("US","JP","KR"), 
         start = "1995",
         return_raw = TRUE, 
         freq = "A", 
         print_url = TRUE)
```
you get...
http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/DOT/.US+JP+KR.TMG_FOB_USD?startPeriod=1995&endPeriod=2021

which does not return any data.


But if you add "AU" as a country to that list, you do get data with...
http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/DOT/.AU+US+JP+KR.TMG_FOB_USD?startPeriod=1995&endPeriod=2021

So I guess either there is something wrong currently with their API, or they actually do not have data for specifically that indicator for those countries with that frequency, etc.

**Comment by cjyetman** [comment]
I don't have privileges to close issues here, so if you feel this issue is resolved, please close it yourself.
