### ISSUE TITLE
imf_ids() does not list WEO (World Economic Outlook)

### ISSUE THREAD

**Issue by GitHunter0** [christophergandrud/imfr#36]
`imfr::imf_ids()` does not list the **World Economic Outlook (WEO)**, only the **Western Hemisphere Regional Economic Outlook (WHDREO)**

`imfr::imf_ids()` does not seem to list all IMF databases, is there a particular reason for that?

Thank you

**Comment by cjyetman** [comment]
`imfr::imf_ids()` gets and parses the results from this URL: http://dataservices.imf.org/REST/SDMX_JSON.svc/Dataflow

according to this page, that is the proper URL to get "the list of the datasets, registered for the Data Service.": https://datahelp.imf.org/knowledgebase/articles/667681-json-restful-web-service

**Comment by GitHunter0** [comment]
Thank you @cjyetman , so the problem must be on the IMF side... I will try to find a way to contact them.
