### ISSUE TITLE
Using IMFR to read GSMAB data

### ISSUE THREAD

**Issue by rmcnab67** [christophergandrud/imfr#4]
Hi,
First, thanks for contributing IMFR.  As a novice R user, this looks like a very help contribution.

Background: I am attempting to use IMFR to read the IMF's Government FInancial Statistics data. I'm starting out with the Main Aggregates database and while IMFR works perfect for the IFS database, I am having difficulties. The GFSMAB database contains data on central, state, and local government revenues and expenditures.

I kept everything the same as your original example.

The error I receive is: "Error: GF2M is not available for your query."  I have used another github project to verify I can read the data but would prefer IMFR since it creates a panel dataset from the query.

library(imfr)

real_ex <- imf_data(database_id = 'GFSMAB', indicator = 'GF2M',
                    country = c('CN', 'GB'), freq = 'A',
                    start = 1989, end = 2013)

However, when I change the code to make the indicator a level of government, such as "S1311" which is the central government, then it downloads all the available data but no way to differeniate between variables as it's downloaded into one column.

real_ex <- imf_data(database_id = 'GFSMAB', indicator = 'S1311', 
                    country = c('US', 'GB'), freq = 'A',
                    start = 1989, end = 2013)

So, my question is whether I can have an indicator for the variable I want (say, GF2M) and the level of government?

Thanks in advance for any assistance.

**Comment by christophergandrud** [comment]
Thanks for you query. I haven't looked into the GFS data set before with imfr. This might require further development of the package's internal infrastructure.

In the meantime you can probably use the argument `return_raw = TRUE` to return the raw JSON and then process it into a data frame using a package like jsonlite.

**Comment by msh855** [comment]
Hi, 

I make this call: 

```
Assets<-imf_data(database_id='BOP', indicator= "BFPAECB_BP6_USD", country = "all", start = 2000,
         end = current_year(), freq = "Q")
```

But it appears this error: 

`Error: BFPAECB_BP6_USD is not available for your query.`

I checked and the indicator it exists. So, must be something else that needs debugging.

**Comment by christophergandrud** [comment]
Does the indicator exist for the query you provided? E.g. for all countries from 2000 to the current year in a quarterly frequency?

**Comment by msh855** [comment]
Not for all countries but the indicator exists at quarterly frequency. I have the bulk data from IMF site.

**Comment by christophergandrud** [comment]
I would specify the countries you want and know there is data for, e.g.:

```R
Assets<-imf_data(database_id='BOP', indicator= "BFPAECB_BP6_USD", 
                 country = c('RU', 'FR'), start = 2000,
                 end = current_year(), freq = "Q")
```

A longer term project would be to improve how imfr addresses exceptions.
