### ISSUE TITLE
DOTS database

### ISSUE THREAD

**Issue by DuongTSon** [christophergandrud/imfr#5]
Hi,

Thank you for your package!
As a macroeconomic researcher, your package help me automate a huge portion of data collection process.
However, there is one issue that I have found when I attempted to download data from Direction of Trade Statistics. The issue is the counterpart_area column in the database is not imported since there is no counterpart_area argument in the imf_data function.

Could you suggest any fix for the issue?

Thank you in advance for your help!

**Comment by christophergandrud** [comment]
Thanks for getting in touch @DuongTSon. 

Could you provide a little example of what you would like to do to help me address this?

**Comment by DuongTSon** [comment]
Hi,

I am trying to calculate the nominal and real effective exchange rate of a currency, so I need data of trades between a country and the rest of the world. The IMF Direction of Trade Statistics (DOTS) database is my data source. I use the code below for download export data from DOTS :

`data<-imf_data(database_id="DOT",indicator="TXG_FOB_USD",country="US",print_url=T)`

However, the data retrieved contains only 3 columns, i.e. , iso2c, year and TXG_FOB_USD. That lack the counterpart_area of the country which I could found in [http://data.imf.org/regular.aspx?key=61013712](url).

Hope that could help you address the issue!

**Comment by christophergandrud** [comment]
Sorry for the delay in getting back to you on this.

I should have pointed out that a solution already exists within **imfr** (though there was a bug that I fixed in the most recent commit https://github.com/christophergandrud/imfr/commit/87b8604bd5807f7edf0093f372844120574ec01c, so reinstall the package with: `devtools::install_github('christophergandrud/imfr').

Basically, you don't want to have **imfr** subset the resulting data frame to include just the country, time, and variable identifiers. So you can have it return the raw full version of the data set with the `return_raw` argument:

```R
data_list <- imf_data(database_id = "DOT", indicator = "TXG_FOB_USD", 
                      country = "US", return_raw = TRUE)
``` 

This will give you the full data set as a list. Then just extract the data frame part:

```R
data_df <- data_list$CompactData$DataSet$Series
```

You should be able to find the variables you want in this. 

I think I should improve the README to include an example of this.

**Comment by christophergandrud** [comment]
I still need to do some work to simplify the process of cleaning up that object.

**Comment by DuongTSon** [comment]
Hi,
Thank you for update the issue.
After hours of cracking the problem. I have modify the imf_data function so I could retrieve data from DOTS. However, it only apply to DOT database, the code is:

`imf_dot<- function(indicator,country="VN",counterpart="US",start=1995,end=2016,freq="A")
{ if(length(indicator)>1)
    stop("Only use one indicator a time", call.=TRUE)
  else {
    url<-paste("http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/","DOT/",freq,".",country,".",indicator,"?startPeriod=",start,"&endPeriod=",end,sep="")
    data<-fromJSON(url)
    data<-as.data.frame(data)
    
    for (i in counterpart){
      temp<-subset(data,data$CompactData.DataSet.Series..COUNTERPART_AREA==i)
      temp<-as.data.frame(temp$CompactData.DataSet.Series.Obs)
      temp<-temp[,1:2]
      colnames(temp)<-c("year",i)
      if (grep(i,counterpart)==1)
        combined<-temp
      else {
        by_id<-colnames(temp)[1]
        combined<-merge(combined,temp,by=by_id,all=TRUE)
      }
    }
  }

  if (nrow(combined)==0)
    stop("No data found.",call.=TRUE)
  remove(data,temp,i)
  return(combined)
}

for (i in indicators){
  d<-imf_dot(indicator=i,country="VN",counterpart=counterpart.area,start=1995,end=2016,freq="A")
  d<-apply(d,2,as.numeric)
  assign(i,d)
}`
I hope that could make a small improvement to your package.
Thank you for making a wonderful package!

**Comment by christophergandrud** [comment]
Thanks. 

It is really difficult to come up with a general purpose solution given the variety of data formats in this database.
