### ISSUE TITLE
No longer working - lexical error message

### ISSUE THREAD

**Issue by KevinKotze** [christophergandrud/imfr#7]
All was working well until two weeks ago. After executing any command, I now get a lexical error message. Here is an example:

> library("imfr")
> real_ex <- imf_data(database_id='IFS', indicator='EREER_IX', country='ZM', freq='A', start=2001, end=2007, print_url=TRUE, times=5)
Attempting to download from: http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/IFS/.ZM.EREER_IX?startPeriod=2001&endPeriod=2007
Downloading: 550 B     
Error: lexical error: invalid char in json text.
                                       <html xmlns="http://www.w3.org/
                     (right here) ------^

When I plug the URL that is provided into my Firefox browser the data is all there. Have tried different machines and have also updated the package from GitHub. Please help.

**Comment by christophergandrud** [comment]
Hm seems like there has been a change in the API. 

Thanks for reporting. I'll look into this.

**Comment by christophergandrud** [comment]
The error occurs because `GET` returns a "Request Rejected" error at [here](https://github.com/christophergandrud/imfr/blob/master/R/utils.R#L97).

I'm not sure why this happens now, especially because as you point out entering the URL directly in the browser seems to work fine.

More work needed . . .

**Comment by KevinKotze** [comment]
Exact same problem with the package "mingjerli/IMFData"

**Comment by cjyetman** [comment]
apparently they don't like httr's default user-agent string "libcurl/7.51.0 r-curl/2.3 httr/1.2.1"

if you add `user_agent("httr")` to the `GET` request it works
```r
library(httr)
library(jsonlite)

URL <- "http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/IFS/.ZM.EREER_IX?startPeriod=2001&endPeriod=2007"

raw_download <- RETRY("GET", URL, progress(), times = times) %>% 
  content(type = "text", encoding = "UTF-8")
jsonlite::fromJSON(raw_download)

raw_download <- RETRY("GET", URL, user_agent("httr"), progress(), times = times) %>% 
  content(type = "text", encoding = "UTF-8")
jsonlite::fromJSON(raw_download)

```

**Comment by christophergandrud** [comment]
Thanks @cjyetman! I merged the pull request. Will do some quick documentation update and then push to CRAN.

**Comment by cjyetman** [comment]
in case @KevinKotze or others don't realize, they can install the github/dev version now and it will already work...
```r
devtools::install_github('christophergandrud/imfr')
```

**Comment by KevinKotze** [comment]
Many thanks! All working well and thanks for a great package.
